[package]
name = "waaaa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures-util = { version = "0.3.30", default-features = false, features = ["sink"] }

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
tokio = "1.36"
tokio-tungstenite = "0.21.0"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
gloo-net = { version = "0.5.0", features = ["websocket"] }
